version: 1
default_environment: dev
project_id: prodder-demo-project-public
plugins:
  extractors:
  - name: tap-toggl
    namespace: tap_toggl
    pip_url: git+https://github.com/AutoIDM/tap-toggl.git@current_time_entries
    executable: tap-toggl
    capabilities:
    - catalog
    - discover
    - state
    settings:
    - name: api_token
      kind: password
    - name: detailed_report_trailing_days
      kind: integer
    - name: start_date
      kind: string
    - name: user_agent
      kind: string
  - name: tap-duckdb
    namespace: tap_duckdb
    pip_url: git+https://github.com/MeltanoLabs/tap-duckdb.git duckdb==0.6.1
    capabilities:
    - state
    - catalog
    - discover
    config:
      path: $MELTANO_PROJECT_ROOT/output/prodder.duckdb
    select:
    - autoidm-target_slack.*
  loaders:
  - name: target-apprise
    namespace: target_apprise
    pip_url: target-apprise
    executable: target-apprise
    settings:
    - name: uris
      kind: array
  - name: target-duckdb
    variant: jwills
    pip_url: target-duckdb~=0.4 duckdb==0.6.1
    config:
      filepath: $MELTANO_PROJECT_ROOT/output/prodder.duckdb
      default_target_schema: $MELTANO_EXTRACT__LOAD_SCHEMA
  transformers:
  - name: dbt
    pip_url: dbt-core~=1.2.0 dbt-duckdb~=1.2.0 duckdb==0.6.1
    config:
      target: duckdb
      path: $MELTANO_PROJECT_ROOT/output/prodder.duckdb
      project_dir: $MELTANO_PROJECT_ROOT/transform
      PROFILES_DIR: $MELTANO_PROJECT_ROOT/transform/profile
      source_schema: $MELTANO_LOAD__TARGET_SCHEMA
      target_schema: autoidm
      models: my_meltano_project
environments:
- name: dev
  config:
    plugins:
      extractors:
      - name: tap-toggl
        config:
          detailed_report_trailing_days: 3
          start_date: '2023-05-03'
          user_agent: AutoIDM
- name: staging
- name: prod
  config:
    plugins:
      extractors:
      - name: tap-toggl
        config:
          detailed_report_trailing_days: 3
          start_date: '2023-05-03'
          user_agent: AutoIDM
      loaders:
      - name: target-postgres
        config:
          host: postgres
- name: sandbox
jobs:
- name: prodder
  tasks:
  - tap-toggl target-duckdb dbt:run tap-duckdb target-apprise
schedules:
- name: twice_an_hour_during_business_hours
  interval: '*/23 13-22 * * 1-5' #8-17 EST, cron is in UTC
  job: prodder